formatter: "md table" # this is required

version: ""

header-from: main.tf
footer-from: ""

recursive:
  enabled: false
  path: modules
  include-main: true

sections:
  hide: []
  show: []

  hide-all: false # deprecated in v0.13.0, removed in v0.15.0
  show-all: true  # deprecated in v0.13.0, removed in v0.15.0

content: ""

output:
  file: ""
  mode: inject
  template: |-
    # ip-terraform-doc
    ip terraform doc

    # Important
    1. Generate documentation
    ```
    terraform-docs -c .terraform-docs.yml --output-file README.md --output-mode replace .
    ```

    2. Generate terraform.tfvars
    ```
    terraform-docs tfvars hcl /path/to/module

    terraform-docs tfvars json /path/to/module
    ```

    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->    

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true